---
- name: "sysconf : Turn off coredumps"
  become: true
  sysctl:
    name: kernel.core_pattern
    state: present
    value: " "
    sysctl_file: /etc/sysctl.d/80-coredump.conf
  notify: Reload sysctl

- name: "sysconf : Turn {{ sysconf_selinux_onoff }} SELinux"
  become: true
  selinux:
    state: "{{ sysconf_selinux | ternary('permissive', 'disabled') }}"

- name: "sysconf : Turn on/off services"
  become: true
  systemd:
    name: "{{ item.key }}.service"
    enabled: "{{ item.value }}"
    state: "{{ item.value | ternary('started', 'stopped') }}"
  with_dict: "{{ sysconf_services }}"

- name: "sysconf : Turn on/off timers"
  become: true
  systemd:
    name: "{{ item.key }}.timer"
    enabled: "{{ item.value }}"
    state: "{{ item.value | ternary('started', 'stopped') }}"
  with_dict: "{{ sysconf_timers }}"

- name: "sysconf : Shells"
  become: true
  lineinfile:
    path: "/etc/shells"
    line: "{{ item }}"
  loop: "{{ sysconf_shells }}"

- name: "sysconf : Add directories"
  become: true
  file:
    state: directory
    path: "/{{ item.path }}"
  loop: >-
    {{ lookup('filetree', '.')
     | selectattr('state', 'equalto', 'directory')
    }}

- name: "sysconf : Add files"
  become: true
  copy:
    src: "{{ item.path }}"
    dest: "/{{ item.path }}"
    mode: "{{ item.mode }}"
  loop: >-
    {{ lookup('filetree', '.')
     | selectattr('state', 'equalto', 'file')
     | selectattr('path', 'regex', '[^~#]$')
    }}
