---
work:
  ssh_known_hosts: {}
  flatpak_apps: []

  dnf_repos_custom:
    - repo: https://download.docker.com/linux/fedora/docker-ce.repo

  dnf_packages_present:
    - containerd.io
    - docker-buildx-plugin
    - docker-ce
    - docker-ce-cli
    - docker-compose-plugin
    - git-review
    - libpq-devel
    - libxslt-devel
    - python3.11-devel

  users:
    mattiasb:
      groups:
        - docker

  gnome_settings:
    # Work monitor
    /org/gnome/desktop/interface/document-font-name: "'Cantarell 14'"
    /org/gnome/desktop/interface/font-name: "'Cantarell 14'"
    /org/gnome/desktop/wm/preferences/titlebar-font: "'Cantarell Bold 14'"
    /org/gnome/desktop/interface/monospace-font-name: >-
      'JetBrains Mono Medium 15'

  gnome_favorite_apps: []

  url_install: {}

  bashcomp_commands: {}

  languages_python:
    azure-cli:
    pre-commit:
      version: 3.5.0

  languages_go: {}

ssh_known_hosts: >-
  {{ groupvars.all.ssh_known_hosts | combine(work.ssh_known_hosts) }}

flatpak_apps: >-
  {{ groupvars.all.flatpak_apps | union(work.flatpak_apps) }}

dnf_repos_custom: >-
  {{ groupvars.all.dnf_repos_custom | union(work.dnf_repos_custom) }}

dnf_packages_present: >-
  {{ groupvars.all.dnf_packages_present | union(work.dnf_packages_present) }}

gnome_favorite_apps: >-
  {{ groupvars.all.gnome_favorite_apps
   | union(work.gnome_favorite_apps)
  }}

bashcomp_commands: >-
  {{ groupvars.all.bashcomp_commands
   | combine(work.bashcomp_commands, recursive=True)
  }}

languages_python: >-
  {{ groupvars.all.languages_python
   | combine(work.languages_python, list_merge="append_rp")
  }}

languages_go: >-
  {{ groupvars.all.languages_go | combine(work.languages_go) }}

url_install: >-
  {{ groupvars.all.url_install
   | combine(work.url_install, recursive=True)
  }}

gnome_settings: >-
  {{ groupvars.all.gnome_settings
   | combine(work.gnome_settings, recursive=True)
  }}

users: >-
  {{ groupvars.all.users
   | combine(work.users, recursive=True, list_merge="append_rp")
  }}

ssh_lastpass_key: Keys/ssh-mattiasb-work
