---
work:
  ssh_known_hosts:
    git.smarteye.se: 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAwp+mYqOm2QCwU3t9aO0dM
jeroCPlFNUNHsdFXKGb9DWRuN2m4OPQPioEgIIaE91gHZ89OIi4lcGqDeGISIEZpVGLQXlnG0RVfrGg
Dv8/oQT2y60m298zJXRU2voVCJGFdcjYDfPsaaAJ3ICRaUf1wivdzCvT+V8/cPwCMIPgefUZMW0E1xW
W6IOvY/QHUzxzguouQLwP5BU+H6UDqpJEodNvYFuDZ248JpL4HB5mx8t41R//6i6aVnpJ5teq3dbNtI
79wzz3ijxh9g+pKpL89J8LrfQvePL8DBIqk/6R6bAkdrAQrtQ6dnU5DGgA6t8fpH+orXXGXmQUxCmLq
Z3+WQ=='
  flatpak_apps: []
  dnf_packages_present:
    - python3.8
    - moby-engine

  gnome_favorite_apps:
    - org.gnome.Fractal
    - com.microsoft.Teams
    - org.remmina.Remmina
    - org.gnome.Boxes

  url_install:
    executables:
      - url: https://dl.k8s.io/release/v1.19.9/bin/linux/amd64/kubectl
        sha: "sha256:7128c9e38ab9c445a3b02d3d0b3f0f15fe7fbca56fd87b84e575d7b29e\
999ad9"

  bashcomp_commands:
    kubectl: completion bash

ssh_known_hosts: >-
  {{ groupvars.all.ssh_known_hosts | combine(work.ssh_known_hosts) }}

flatpak_apps: >-
  {{ groupvars.all.flatpak_apps | union(work.flatpak_apps) }}

dnf_packages_present: >-
  {{ groupvars.all.dnf_packages_present | union(work.dnf_packages_present) }}

gnome_favorite_apps: >-
  {{ groupvars.all.gnome_favorite_apps
   | union(work.gnome_favorite_apps)
  }}

bashcomp_commands: >-
  {{ groupvars.all.bashcomp_commands
   | combine(work.bashcomp_commands, recursive=True)
  }}

url_install: >-
  {{ groupvars.all.url_install
   | combine(work.url_install, recursive=True)
  }}

ssh_lastpass_key: Keys/ssh-mattiasb-work
