---
work:
  ssh_known_hosts: {}
  flatpak_apps: []

  dnf_repos_custom: {}

  dnf_packages_present: {}

  users:
    mattiasb:
      groups: []

  gnome_settings: {}

  gnome_favorite_apps: []

  url_install: {}

  bashcomp_commands: {}

  languages_python: {}

  languages_go: {}

ssh_known_hosts: >-
  {{ groupvars.all.ssh_known_hosts | combine(work.ssh_known_hosts) }}

flatpak_apps: >-
  {{ groupvars.all.flatpak_apps | union(work.flatpak_apps) }}

dnf_repos_custom: >-
  {{ groupvars.all.dnf_repos_custom | union(work.dnf_repos_custom) }}

dnf_packages_present: >-
  {{ groupvars.all.dnf_packages_present | union(work.dnf_packages_present) }}

gnome_favorite_apps: >-
  {{ groupvars.all.gnome_favorite_apps
   | union(work.gnome_favorite_apps)
  }}

bashcomp_commands: >-
  {{ groupvars.all.bashcomp_commands
   | combine(work.bashcomp_commands, recursive=True)
  }}

languages_python: >-
  {{ groupvars.all.languages_python
   | combine(work.languages_python, list_merge="append_rp")
  }}

languages_go: >-
  {{ groupvars.all.languages_go | combine(work.languages_go) }}

url_install: >-
  {{ groupvars.all.url_install
   | combine(work.url_install, recursive=True)
  }}

gnome_settings: >-
  {{ groupvars.all.gnome_settings
   | combine(work.gnome_settings, recursive=True)
  }}

users: >-
  {{ groupvars.all.users
   | combine(work.users, recursive=True, list_merge="append_rp")
  }}

ssh_lastpass_key: Keys/ssh-mattiasb-work
