---
work:
  ssh_known_hosts: {}
  flatpak_apps: []
  dnf_packages_present:
    - libxslt-devel
    - libpq-devel

  gnome_settings:
    /org/gnome/desktop/interface/document-font-name: "'Cantarell 14'"
    /org/gnome/desktop/interface/font-name: "'Cantarell 14'"
    /org/gnome/desktop/wm/preferences/titlebar-font: "'Cantarell Bold 14'"
    /org/gnome/desktop/interface/monospace-font-name: >-
      'JetBrains Mono Medium 15'

  gnome_favorite_apps:
    - com.microsoft.Teams
    - org.gnome.Boxes
    - org.gnome.Fractal

  url_install: {}

  bashcomp_commands: {}

  languages_python3:
    - azure-cli
    - pre-commit==3.5.0

  languages_go: {}

ssh_known_hosts: >-
  {{ groupvars.all.ssh_known_hosts | combine(work.ssh_known_hosts) }}

flatpak_apps: >-
  {{ groupvars.all.flatpak_apps | union(work.flatpak_apps) }}

dnf_packages_present: >-
  {{ groupvars.all.dnf_packages_present | union(work.dnf_packages_present) }}

gnome_favorite_apps: >-
  {{ groupvars.all.gnome_favorite_apps
   | union(work.gnome_favorite_apps)
  }}

bashcomp_commands: >-
  {{ groupvars.all.bashcomp_commands
   | combine(work.bashcomp_commands, recursive=True)
  }}

languages_python3: >-
  {{ groupvars.all.languages_python3 | union(work.languages_python3) }}

languages_go: >-
  {{ groupvars.all.languages_go | combine(work.languages_go) }}

url_install: >-
  {{ groupvars.all.url_install
   | combine(work.url_install, recursive=True)
  }}

gnome_settings: >-
  {{ groupvars.all.gnome_settings
   | combine(work.gnome_settings, recursive=True)
  }}

ssh_lastpass_key: Keys/ssh-mattiasb-work
