---
work:
  ssh_known_hosts:
    git.smarteye.se: 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAwp+mYqOm2QCwU3t9aO0dM
jeroCPlFNUNHsdFXKGb9DWRuN2m4OPQPioEgIIaE91gHZ89OIi4lcGqDeGISIEZpVGLQXlnG0RVfrGg
Dv8/oQT2y60m298zJXRU2voVCJGFdcjYDfPsaaAJ3ICRaUf1wivdzCvT+V8/cPwCMIPgefUZMW0E1xW
W6IOvY/QHUzxzguouQLwP5BU+H6UDqpJEodNvYFuDZ248JpL4HB5mx8t41R//6i6aVnpJ5teq3dbNtI
79wzz3ijxh9g+pKpL89J8LrfQvePL8DBIqk/6R6bAkdrAQrtQ6dnU5DGgA6t8fpH+orXXGXmQUxCmLq
Z3+WQ=='
  flatpak_apps:
    - name: com.mattermost.Desktop
      remote: flathub
  dnf_packages_present:
    - icedtea-web

ssh_known_hosts: >-
  {{ groupvars.all.ssh_known_hosts | combine(work.ssh_known_hosts) }}

flatpak_apps: >-
  {{ groupvars.all.flatpak_apps | union(work.flatpak_apps) }}

dnf_packages_present: >-
  {{ groupvars.all.dnf_packages_present | union(work.dnf_packages_present) }}
