#!/usr/bin/env ansible-playbook
---
- name: System
  hosts: "{{ lookup('pipe', 'hostname') }}"
  become: true
  tags: system
  gather_facts: false
  tasks:
    - name: "Sudo password"
      # Need to list all tags in this play instead of using `always` since
      # otherwise Ansible will run this even when *only* setting the `user` tag.
      tags:
        - system
        - prerequisites
        - dnf
        - flatpak-system-clean
        - sysconf
      block:
        - pause:
            prompt: "Sudo password"
            echo: false
          register: result
        - set_fact:
            ansible_become_pass: "{{ result.user_input }}"

        # Need this since Ansible otherwise won't gather_facts on tagged runs.
        - name: "Gather facts"
          setup:

    - name: "Install prerequisites"
      tags: prerequisites
      dnf:
        state: present
        name:
          - python3-psutil
          - python3-libselinux

    - name: dnf
      tags: dnf
      block:
        - include_role:
            name: dnf

    - name: flatpak-system-clean
      tags: flatpak-system-clean
      block:
        - include_role:
            name: flatpak-system-clean

    - name: sysconf
      tags: sysconf
      block:
        - include_role:
            name: sysconf

- name: User
  hosts: "{{ lookup('pipe', 'hostname') }}"
  tags: user
  tasks:
    - name: Get users homedir
      tags: always
      set_fact:
        homedir: "{{ lookup('pipe', 'command echo ~') }}"

    - name: gnome
      tags: gnome
      block:
        - include_role:
            name: gnome

    - name: lastpass
      tags: lastpass
      block:
        - include_role:
            name: lastpass

    - name: ssh
      tags: ssh
      block:
        - include_role:
            name: ssh

    - name: userconf
      tags: userconf
      block:
        - include_role:
            name: userconf

    - name: git
      tags: git
      block:
        - include_role:
            name: git

    - name: flatpak
      tags: flatpak
      block:
        - include_role:
            name: flatpak

    - name: languages
      tags: languages
      block:
        - include_role:
            name: languages

    - name: url-install
      tags: url-install
      block:
        - include_role:
            name: url-install

    - name: bashcomp
      tags: bashcomp
      block:
        - include_role:
            name: bashcomp

    - name: git-install
      tags: git-install
      block:
        - include_role:
            name: git-install
