#!/usr/bin/env ansible-playbook
---
- hosts: "{{ lookup('pipe', 'hostname') }}"
  become: true
  tags:
    - prerequisites
    - dnf
    - sysconf
    - system
  tasks:
    - name: "Install prerequisites"
      dnf:
        state: present
        name:
          - python3-psutil
          - python3-libselinux
      tags: prerequisites

    - name: dnf
      block:
        - include_role:
            name: dnf
      tags: dnf

    - name: sysconf
      block:
        - include_role:
            name: sysconf
      tags: sysconf

- hosts: "{{ lookup('pipe', 'hostname') }}"
  tags:
    - user
  tasks:
    - name: Get users homedir
      set_fact:
        homedir: "{{ lookup('pipe', 'command echo ~') }}"
      tags: always

    - name: gnome
      block:
        - include_role:
            name: gnome
      tags: gnome

    - name: lastpass
      block:
        - include_role:
            name: lastpass
      tags: lastpass

    - name: ssh
      block:
        - include_role:
            name: ssh
      tags: ssh

    - name: userconf
      block:
        - include_role:
            name: userconf
      tags: userconf

    - name: git
      block:
        - include_role:
            name: git
      tags: git

    - name: flatpak
      block:
        - include_role:
            name: flatpak
      tags: flatpak

    - name: languages
      block:
        - include_role:
            name: languages
      tags: languages

    - name: url-install
      block:
        - include_role:
            name: url-install
      tags: url-install

    - name: bashcomp
      block:
        - include_role:
            name: bashcomp
      tags: bashcomp

    - name: git-install
      block:
        - include_role:
            name: git-install
      tags: git-install
