#!/usr/bin/env ansible-playbook
---
- hosts: "{{ lookup('pipe', 'hostname') }}"
  become: true
  tasks:
    - name: "Install prerequisites"
      vars:
        libselinux:
          30: libselinux-python
          31: python3-libselinux
          32: python3-libselinux
      dnf:
        state: present
        name:
          - python3-psutil
          - "{{ libselinux[ansible_distribution_major_version | int] }}"
      tags: prerequisites

    - name: dnf
      include_role:
        name: dnf
      tags: dnf

    - name: sysconf
      include_role:
        name: sysconf
      tags: sysconf

- hosts: "{{ lookup('pipe', 'hostname') }}"
  tasks:
    - name: gnome
      include_role:
        name: gnome
      tags: gnome

    - name: lastpass
      include_role:
        name: lastpass
      tags: lastpass

    - name: ssh
      include_role:
        name: ssh
      tags: ssh

    - name: userconf
      include_role:
        name: userconf
      tags: userconf

    - name: git
      include_role:
        name: git
      tags: git

    - name: bashcomp
      include_role:
        name: bashcomp
      tags: bashcomp

    - name: flatpak
      include_role:
        name: flatpak
      tags: flatpak

    - name: languages
      include_role:
        name: languages
      tags: languages

    - name: git-install
      include_role:
        name: git-install
      tags: git-install
