---
mattiasb_lenovo_yoga920:
  gnome_settings: {}
#     /org/gnome/desktop/wm/keybindings/close: "['AudioMicMute']"

gnome_settings: >-
  {{ groupvars.all.gnome_settings
   | combine(private.gnome_settings)
   | combine(mattiasb_lenovo_yoga920.gnome_settings)
  }}
