---
mattiasb_dell_5401:
  gnome_favorite_apps: []
#     /org/gnome/desktop/wm/keybindings/close: "['AudioMicMute']"

gnome_favorite_apps: >-
  {{ groupvars.all.gnome_favorite_apps
   | union(work.gnome_favorite_apps)
   | union(mattiasb_dell_5401.gnome_favorite_apps)
  }}
