---
mattiasb_lenovo_yoga920:
  gnome_favorite_apps: []
#     /org/gnome/desktop/wm/keybindings/close: "['AudioMicMute']"

gnome_favorite_apps: >-
  {{ groupvars.all.gnome_favorite_apps
   | union(private.gnome_favorite_apps)
   | union(mattiasb_lenovo_yoga920.gnome_favorite_apps)
  }}
