---

## Groupvars

groupvars:
  all: "{{ hostvars['group-all'] }}"
  private: "{{ hostvars['group-private'] }}"
  test: "{{ hostvars['group-test'] }}"
  work: "{{ hostvars['group-work'] }}"


## Ansible

ansible_connection: local
ansible_python_interpreter: /usr/bin/python3


## DNF

dnf_repos:
  google-chrome: false

dnf_repos_rpmfusion:
  free: true
  nonfree: true

dnf_repos_custom: []

dnf_packages_absent:
  - gedit
  - gnome-terminal
  - podman-docker
  - rhythmbox
  - shotwell

dnf_packages_present:
  - "@development-tools"
  - "@Virtualization"
  - "@c-development"
  - "@development-libs"
  - "@development-tools"
  - ShellCheck
  - adw-gtk3-theme
  - asciidoc
  - bat
  - bison
  - btop
  - cabal-install
  - cargo
  - cascadia-fonts-all
  - clang-devel
  - cloc
  - cmake
  - codespell
  - colorized-logs
  - ddcutil
  - difftastic
  - direnv
  - docbook-dtds
  - docbook-style-xsl
  - dotnet-sdk-8.0
  - emacs
  - enchant2-devel
  - epiphany
  - evolution
  - evolution-ews
  - flatpak
  - flatpak-builder
  - flex
  - fzf
  - gawk
  - gettext
  - ghc-compiler
  - gimp
  - git
  - git-delta
  - gnome-calendar
  - gnome-common
  - gnome-console
  - gnome-maps
  - gnome-photos
  - gnome-tweak-tool
  - golang
  - golang-godoc
  - golang-x-tools-gopls
  - gperf
  - gstreamer1-libav
  - gstreamer1-plugins-bad-freeworld
  - gstreamer1-plugins-ugly
  - gstreamer1-vaapi
  - hdparm
  - htop
  - httpie
  - hunspell-sv
  - intltool
  - iperf3
  - jetbrains-mono-fonts
  - jq
  - lastpass-cli
  - libatomic
  - libcurl-devel
  - librsvg2-tools
  - libva-intel-driver
  - libxslt
  - livecd-tools
  - llvm-devel
  - llvm-static
  - lshw
  - makepasswd
  - meld
  - meson
  - moreutils
  - nautilus-dropbox
  - ncurses-devel
  - nmap
  - nodejs-bash-language-server
  - npm
  - openldap-clients
  - openssl-devel
  - p7zip-plugins
  - pandoc
  - perl-Errno
  - perl-open
  - podman
  - podman-compose
  - powerline
  - powerline-go
  - ptyxis
  - python-devel
  - python-pip
  - python3-devel
  - python3.13
  # Issue On F49 Beta. Installed with uv instead.
  # - python3-csvkit
  - ragel
  - remmina
  - remmina-plugins-rdp
  - remmina-plugins-vnc
  - reuse
  - ripgrep
  - ruby
  - ruby-devel
  - ruby-irb
  - rust
  - rust-analyzer
  - rustfmt
  - systemd-container
  - texlive-beamer
  - tig
  - tmux
  - tmux-powerline
  - transmission-remote-gtk
  - typescript
  - unrar
  - uv
  - vagrant
  - wireshark
  - wl-clipboard
  - xmlto
  - xorriso
  - xprop
  - xxd
  - yamllint
  - yelp-tools
  - yubikey-manager
  - yubikey-manager-qt
  - zlib-devel
  - zlib-static


## Flatpak System Clean
flatpak_system_clean: true


## Containers

# TODO: Create containers_conf role that lets me edit stuff in `/etc/containers`


## Udev

udev_rules:
  61-mutter-primary-gpu:
    - - SUBSYSTEM=="drm"
      - SUBSYSTEMS=="pci"
      - ENV{DEVTYPE}=="drm_minor"
      - ENV{DEVNAME}=="/dev/dri/card[0-9]"
      - ATTRS{vendor}=="0x1002"
      - ATTRS{device}=="0x73ff"
      - TAG+="mutter-device-preferred-primary"

## SysConf

sysconf_selinux: false
sysconf_coredumps: false

sysconf_services:
  firewalld: false
  livesys: false


## Users

users:
  mattiasb:
    shell: /usr/local/bin/bash
    groups:
      - libvirt
      - wheel
      - wireshark


######################

## GNOME

gnome_settings:
  /org/freedesktop/ibus/panel/emoji/hotkey: '@as []'
  /org/freedesktop/ibus/panel/emoji/unicode-hotkey: '@as []'
  /org/freedesktop/ibus/panel/show-icon-on-systray: "false"
  /org/gnome/Weather/automatic-location: "true"
  /org/gnome/desktop/calendar/show-weekdate: "true"
  /org/gnome/desktop/datetime/automatic-timezone: "true"
  /org/gnome/desktop/input-sources/xkb-options: "['compose:caps']"
  /org/gnome/desktop/interface/gtk-key-theme: "'Emacs'"
  /org/gnome/desktop/interface/monospace-font-name: "'JetBrains Mono Medium 11'"
  /org/gnome/desktop/peripherals/touchpad/tap-to-click: "true"
  /org/gnome/desktop/search-providers/disable-external: "true"
  /org/gnome/desktop/sound/event-sounds: "false"
  /org/gnome/desktop/wm/keybindings/close: "['<Super>q']"
  /org/gnome/desktop/wm/preferences/action-middle-click-titlebar: "'lower'"
  # See:
  # https://blogs.gnome.org/shell-dev/2024/09/20/understanding-gnome-shells-focus-stealing-prevention/
  # /org/gnome/desktop/wm/preferences/focus-new-windows: "'strict'"
  /org/gnome/evolution/shell/buttons-visible: "false"
  /org/gnome/evolution/shell/show-to-do-bar: "false"
  /org/gnome/nautilus/icon-view/default-zoom-level: "'standard'"
  /org/gnome/nautilus/preferences/click-policy: "'single'"
  /org/gnome/settings-daemon/plugins/color/night-light-enabled: "true"
  /org/gnome/settings-daemon/plugins/media-keys/logout: '@as []'
  /org/gnome/settings-daemon/plugins/power/idle-dim: "false"
  /org/gnome/shell/app-switcher/current-workspace-only: "true"
  /org/gnome/shell/keybindings/toggle-overview: '@as []'
  /org/gnome/shell/keybindings/toggle-quick-settings: '@as []'
  /org/gnome/software/show-upgrade-prerelease: "true"
  /org/gnome/system/locale/region: "'sv_SE.UTF-8'"
  /org/gtk/gtk4/Settings/FileChooser/sort-directories-first: "true"
  /org/gtk/settings/file-chooser/sort-directories-first: "true"

gnome_favorite_apps:
  - io.gitlab.news_flash.NewsFlash
  - dev.geopjr.Tuba
  - org.mozilla.firefox
  - com.spotify.Client
  - org.gnome.Fractal
  - org.signal.Signal
  - com.discordapp.Discord
  - org.gnome.Maps
  - org.gnome.Evolution
  - org.gnome.Calendar
  - org.gnome.Nautilus
  - emacs
  - org.gnome.Ptyxis
  - org.gnome.Software

gnome_mediakeys:
  home: <Super>f
  www: <Super>w

gnome_shell_keybindings:
  screenshot-window: <Super>Print

  screenshot:
  show-screen-recording-ui:
  switch-to-application-1:
  switch-to-application-2:
  switch-to-application-3:
  switch-to-application-4:
  switch-to-application-5:
  switch-to-application-6:
  switch-to-application-7:
  switch-to-application-8:
  switch-to-application-9:

gnome_keybindings:
  move-to-workspace-1: <Super>F1
  move-to-workspace-2: <Super>F2
  move-to-workspace-3: <Super>F3
  move-to-workspace-4: <Super>F4
  move-to-workspace-5: <Super>F5
  move-to-workspace-6: <Super>F6
  move-to-workspace-7: <Super>F7
  move-to-workspace-8: <Super>F8
  move-to-workspace-9: <Super>F9
  move-to-workspace-left: <Super><Shift>Page_Up
  move-to-workspace-right: <Super><Shift>Page_Down
  panel-run-dialog: <Super>r
  switch-applications-backward: <Alt><Super>Tab
  switch-applications: <Alt>Tab
  switch-group-backward: <Shift><Alt>Above_Tab
  switch-group: <Alt>Above_Tab
  cycle-windows-backward: <Shift><Super>Tab
  cycle-windows: <Super>Tab
  cycle-group-backward: <Shift><Super>Above_Tab
  cycle-group: <Super>Above_Tab
  switch-to-workspace-1: <Super>1
  switch-to-workspace-2: <Super>2
  switch-to-workspace-3: <Super>3
  switch-to-workspace-4: <Super>4
  switch-to-workspace-5: <Super>5
  switch-to-workspace-6: <Super>6
  switch-to-workspace-7: <Super>7
  switch-to-workspace-8: <Super>8
  switch-to-workspace-9: <Super>9
  switch-to-workspace-left: <Super>Page_Up
  switch-to-workspace-right: <Super>Page_Down
  unmaximize: <Super>Down

  activate-window-menu:
  begin-move:
  begin-resize:
  cycle-panels-backward:
  cycle-panels:
  switch-panels-backward:
  switch-panels:
  switch-to-workspace-down:
  switch-to-workspace-up:
  toggle-maximized:

gnome_custom_keybindings:
  - name: Calendar
    binding: <Super>c
    command: /bin/gnome-calendar
  - name: Ptyxis
    binding: <Super>e
    command: /bin/ptyxis --new-window
  - name: Emacs
    binding: <Super>s
    command: /bin/emacsclient -c -s main
  - name: NewsFlash
    binding: <Super>n
    command: /bin/flatpak run io.gitlab.news_flash.NewsFlash


## Firefox

# TODO: Make a role to set those configuration variables for Firefox that
#       doesn't seem to sync through the regular channels.
#
# Specifically:
#  - browser.link.open_newwindow = 1
#  - browser.link.open_newwindow.override.external = 2
#
# See: https://support.mozilla.org/en-US/questions/1258193 for the above.


## NewsFlash

news_flash_config:
  general:
    keep_running_in_background: false
    autostart: false
    sync_on_startup: true
    sync_on_metered: true
    sync_every:
      Custom: 600
  advanced:
    proxy: []
    accept_invalid_certs: false
    accept_invalid_hostnames: false
    inspect_article_view: false
    article_view_load_images: true
    ping_url:
      - http://example.com/
      - https://google.com/
  feed_list:
    order: Alphabetical
    only_show_relevant: true
  article_list:
    order: OldestFirst
    show_thumbnails: true
    hide_future_articles: false
  article_view:
    theme: Default
    font: Sans 10
    content_width: 55
    line_height: 1.8
  keybindings:
    general:
      refresh: F5
      search: <Control>f
      quit: <Control>q
    article_view:
      scroll_up: Page_Up
      scroll_down: Page_Down
      scrap_content: c
      fullscreen: f
    article_list:
      next: n
      prev: p
      read: R
      mark: M
      open: O
    feed_list:
      next: <Control>Down
      prev: <Control>Up
      toggle_expanded: null
  share:
    pocket_enabled: true
    instapaper_enabled: false
    twitter_enabled: false
    mastodon_enabled: false
    reddit_enabled: false
    telegram_enabled: false
    clipboard_enabled: true
    custom_enabled: false
    custom_name:
    custom_url:
  feeds: {}


## Lastpass

lastpass_login: true
lastpass_username: "mattias.jc.bengtsson@gmail.com"


## SSH

ssh_lastpass: true
ssh_lastpass_key: Keys/ssh-{{ ansible_hostname }}

ssh_known_hosts:
  github.com: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiip\
                       hnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXa\
                       DbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYf\
                       NqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbL\
                       WNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4z\
                       MjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz\
                       0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnz\
                       tnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0\
                       ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/Wnw\
                       H6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk="
  gitlab.com: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAy\
                                   NTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1f\
                                   Vkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoo\
                                   hFzgbEY="
  gitlab.gnome.org: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbm\
                                         lzdHAyNTYAAABBBOfWUbO2WB8qArojiGnj+Ad5\
                                         1kDIza+4M7VL3VCXAt//fhqHKvbYQBcWaVw2mL\
                                         g1+wRIxM5zDl9ssDhNrvkEN10="

## Userconf

userconf_config_repo_url: git@github.com:mattiasb/.config.git
userconf_services:
  gtk3-color-scheme: true
  lockmon: true
  powerline: false


## git

git_repos:
  github.com:
    - repo: mattiasb/mtg-decks
      dest: "{{ homedir }}/Documents/Magic/decks"
    - repo: mattiasb/.local-bin
      dest: "{{ homedir }}/.local/bin"
    - repo: mattiasb/Code-Test
      dest: "{{ homedir }}/Code/Test"
      version: main
    - repo: mattiasb/MachineSetup
    - repo: mattiasb/mtg-deck-mode


## Bash-completion

bashcomp_commands:
  kubectl: completion bash
  npm: completion
  pandoc: --bash-completion
  talosctl: completion bash
  pip: completion --bash


## Flatpak

flatpak_remotes:
  flathub: https://flathub.org/repo/flathub.flatpakrepo
  gnome-nightly: https://nightly.gnome.org/gnome-nightly.flatpakrepo

flatpak_apps:
  # Flathub
  - name: dev.geopjr.Tuba
    remote: flathub
  - name: com.github.tchx84.Flatseal
    remote: flathub
  - name: com.slack.Slack
    remote: flathub
  - name: com.spotify.Client
    remote: flathub
  - name: im.bernard.Nostalgia
    remote: flathub
  - name: io.gitlab.news_flash.NewsFlash
    remote: flathub
  - name: org.chromium.Chromium
    remote: flathub
  - name: org.gnome.Builder
    remote: flathub
  - name: org.gnome.Fractal
    remote: flathub
  - name: org.gnome.Maps
    remote: flathub
  - name: org.signal.Signal
    remote: flathub
  - name: com.github.cassidyjames.dippi
    remote: flathub
  - name: com.github.maoschanz.drawing
    remote: flathub

  # GNOME Nightly
  - name: org.gnome.Fractal.Devel
    remote: gnome-nightly
  - name: org.gnome.Maps.Devel
    remote: gnome-nightly

## Languages

languages_nodejs:
  - "@devcontainers/cli"
  - eslint
  - typescript-language-server
  - vscode-json-languageserver
  - yaml-language-server

languages_python_version: 3.13
languages_python:
  csvkit:
  ipython:
  mypy:
  pre-commit:
  python-lsp-server:
    features:
      - all
    with:
      - pylsp-mypy
      - python-lsp-ruff
  remarshal:
  sqlparse:
  yamlfix:

languages_rust: []
languages_ruby:
  - rubocop
  - solargraph
languages_go:
  github.com/jmespath/jp: f4ee7271599705d3a55d369ef131b68d99daf2c7
  github.com/noahgorstein/jqp: fe7b5c27089180e1b2848ccf0ef8b3d24a883966
  github.com/helmfile/helmfile: fe1e51e5ef8f89758438920412658f787872dae2

## URL Install

url_install:
  executables:
    - url: https://dl.k8s.io/release/v1.28.3/bin/linux/amd64/kubectl
      sha256: 0c680c90892c43e5ce708e918821f92445d1d244f9b3d7513023bcae9a6246d1
    - name: talosctl
      url: "https://github.com/siderolabs/talos/releases/download/v1.5.4/\
           talosctl-linux-amd64"
      sha256: 98d28410f27028ee7e23335e1901da00accc071e262fcb343c892e18fa6ec9af
  other: []
  #   # TODO: Find out why "{{ homedir }}" doesn't work here for some reason.
  #   # TODO: Support extracting and installing the info file.
  #   #       Manual commands:
  #   #       $ curl -O https://url.to/python-3.12-docs-texinfo.tar.bz2
  #   #       $ tar -jxvf python-3.12-docs-texinfo.tar.bz2
  #   #       $ make infodir=/home/mattiasb/.local/share/info/ install-info
  #   - url: >-
  #       https://docs.python.org/3.12/archives/python-3.12-docs-texinfo.tar.bz2
  #     sha256: 70b337654087f068abfc19db53d1cca7effe45679fec2684ad433880b15aa656
  #     dest: "{{ homedir }}/Downloads/"

## GIT Install

git_install:
  github.com:
    - repo: mattiasb/emacs-2.0
      version: main
      make:
        - install

    - repo: mattiasb/git-fpaste
      version: master
      make:
        - user-install

    - repo: mattiasb/git-wip
      version: master
      make:
        - user-install

    - repo: tobias-johansson/git-each
      version: master
      make:
        - user-install

    - repo: LuyaoHuang/virsh-bash-completion
      version: 87a81d7e7d2c9518d18a8a266153e09ef9b69d6c
      files:
        - src: virsh_bash_completion
          dest: "{{ bashcomp_directory }}/virsh"

    - repo: cykerway/complete-alias
      version: 4fcd018faa9413e60ee4ec9f48ebeac933c8c372
      files:
        - src: complete_alias
          dest: "{{ homedir }}/.config/bash_completion.d/complete_alias"

    - repo: dysosmus/ansible-completion
      version: ad00a6d7850a50420b3febc6a4cc387184a1a5cc
      files:
        - src: ansible-completion.bash
          dest: "{{ bashcomp_directory }}/ansible"
        - src: ansible-doc-completion.bash
          dest: "{{ bashcomp_directory }}/ansible-doc"
        - src: ansible-galaxy-completion.bash
          dest: "{{ bashcomp_directory }}/ansible-galaxy"
        - src: ansible-playbook-completion.bash
          dest: "{{ bashcomp_directory }}/ansible-playbook"
        - src: ansible-pull-completion.bash
          dest: "{{ bashcomp_directory }}/ansible-pull"
        - src: ansible-vault-completion.bash
          dest: "{{ bashcomp_directory }}/ansible-vault"

    - repo: domtronn/all-the-icons.el
      version: master
      files:
        - src: fonts/
          dest: "{{ homedir }}/.local/share/fonts/"
      commands:
        - fc-cache -f -v

    - repo: rainstormstudio/nerd-icons.el
      version: main
      files:
        - src: fonts/
          dest: "{{ homedir }}/.local/share/fonts/"
      commands:
        - fc-cache -f -v

    - repo: emacs-eldev/eldev
      version: 65e00433b5673f18328fc824cbdb54e6f7b872bc
      files:
        - src: /bin/eldev
          dest: "{{ homedir }}/.local/bin/eldev"
          mode: '0755'
