---
- name: "{{ command }} : Get completion script"
  command: "{{ command }} {{ arguments | default('') }}"
  changed_when: false
  register: result
  check_mode: false
  # This just becomes too much
  no_log: true
  environment:
    # TODO: Make this a bit more general instead of having a workaround
    #       specifically for pipenv.
    _PIPENV_COMPLETE: bash_source

- name: "{{ command }} : Write completion script"
  copy:
    content: "{{ result.stdout }}"
    dest: "{{ bashcomp_directory }}/{{ command }}"
