---
- name: "{{ command }} : Get completion script"
  command: "{{ command }} {{ arguments }}"
  changed_when: false
  register: result
  check_mode: false

- name: "{{ command }} : Write completion script"
  copy:
    content: "{{ result.stdout }}"
    dest: "{{ bashcomp_directory }}/{{ command }}"
