---

# Make it possible to run this:
# $ flatpak remote-modify --enable --no-filter flathub

- name: "Flatpak : Add remotes"
  become: true
  flatpak_remote:
    name: "{{ item.key }}"
    flatpakrepo_url: "{{ item.value }}"
    method: user
  with_dict: "{{ flatpak_remotes }}"

- name: "Install apps"
  become: true
  flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote }}"
    method: user
  with_items: "{{ flatpak_apps }}"
