---

- name: "Flatpak : Add remotes"
  become: true
  flatpak_remote:
    name: "{{ item.key }}"
    flatpakrepo_url: "{{ item.value }}"
  with_dict: "{{ flatpak_remotes }}"

- name: "Install apps"
  become: true
  flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote }}"
  with_items: "{{ flatpak_apps }}"
