---
- name: "Install Executables"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ homedir }}/.local/bin/{{ item.name | d('') }}"
    mode: 0755
    checksum: "sha256:{{ item.sha256 }}"
  with_items: "{{ url_install.executables | d([]) }}"

- name: "Install other files"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: 0644
    checksum: "{{ item.sha }}"
  with_items: "{{ url_install.other | d([]) }}"
