---
- name: "git : Clone repositories"
  include_tasks: git_clone.yml
  vars:
    repositories: "{{ item.value }}"
    domain: "{{ item.key }}"
    user: "git"
    version: "{{ item.version | default('master') }}"
  with_dict: "{{ git_repos }}"
