---
private:
  flatpak_remotes:
    flathub-beta: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
  flatpak_apps:
    # Apps
    - name: org.gnome.Books
      remote: flathub
      gtk: true
    - name: org.gnome.Games
      remote: flathub
      gtk: true
    - name: com.valvesoftware.Steam
      remote: flathub
    - name: com.valvesoftware.Steam.CompatibilityTool.Proton
      remote: flathub
    - name: com.github.Anuken.Mindustry
      remote: flathub
    - name: com.discordapp.Discord
      remote: flathub
    - name: de.haeckerfelix.Fragments
      remote: flathub-beta
      gtk: true

  gnome_settings:
    /org/gnome/shell/favorite-apps: >-
      ['firefox.desktop',
       'com.spotify.Client.desktop',
       'org.gnome.Nautilus.desktop',
       'org.gnome.Calendar.desktop',
       'org.gnome.Maps.desktop',
       'org.gnome.Books.desktop',
       'org.gnome.Games.desktop',
       'org.gnome.Terminal.desktop',
       'com.discordapp.Discord.desktop',
       'org.gnome.Fractal.desktop',
       'de.haeckerfelix.Fragments.desktop']

flatpak_remotes: >-
  {{ groupvars.all.flatpak_remotes
   | combine(private.flatpak_remotes)
  }}

flatpak_apps: >-
  {{ groupvars.all.flatpak_apps
   | union(private.flatpak_apps)
  }}

gnome_settings: >-
  {{ groupvars.all.gnome_settings
   | combine(private.gnome_settings)
  }}
