---
private:
  flatpak_remotes:
    flathub-beta: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
  flatpak_apps:
    # Apps
    - name: com.belmoussaoui.Obfuscate
      remote: flathub
    - name: com.discordapp.Discord
      remote: flathub
    - name: com.github.Anuken.Mindustry
      remote: flathub
    - name: com.valvesoftware.Steam
      remote: flathub
    - name: com.valvesoftware.Steam.CompatibilityTool.Proton
      remote: flathub
    - name: de.haeckerfelix.Fragments
      remote: flathub
    - name: net.kirgroup.confy
      remote: flathub
    - name: org.gnome.Podcasts
      remote: flathub
    - name: org.gnome.gitlab.YaLTeR.VideoTrimmer
      remote: flathub
    - name: org.nickvision.tubeconverter
      remote: flathub

  gnome_favorite_apps:
    - com.discordapp.Discord
    - de.haeckerfelix.Fragments
  dnf_packages_absent:
    - docker
    - docker-common

flatpak_remotes: >-
  {{ groupvars.all.flatpak_remotes
   | combine(private.flatpak_remotes)
  }}

flatpak_apps: >-
  {{ groupvars.all.flatpak_apps
   | union(private.flatpak_apps)
  }}

# Use `lists_union` since order is important!
gnome_favorite_apps: >-
  {{ groupvars.all.gnome_favorite_apps
   | community.general.lists_union(private.gnome_favorite_apps)
  }}

dnf_packages_absent: >-
  {{ groupvars.all.dnf_packages_absent | union(private.dnf_packages_absent) }}
