---
private:
  flatpak_remotes:
    gnome-nightly: https://sdk.gnome.org/gnome-nightly.flatpakrepo
    gnome-apps-nightly: https://sdk.gnome.org/gnome-apps-nightly.flatpakrepo
  flatpak_apps:
    # Apps
    - name: org.gnome.Books
      remote: flathub
      gtk: true
    - name: org.gnome.Games
      remote: flathub
      gtk: true
    - name: com.valvesoftware.Steam
      remote: flathub
    # Apps Nightly
    - name: org.gnome.Builder
      remote: gnome-apps-nightly
      gtk: true
    - name: org.gnome.Maps
      remote: gnome-apps-nightly
      gtk: true
    - name: org.gnome.Epiphany
      remote: gnome-apps-nightly
      gtk: true
    - name: org.gnome.Games
      remote: gnome-apps-nightly
      gtk: true
  gnome_settings:
    /org/gnome/shell/favorite-apps: >-
      ['firefox.desktop',
       'com.spotify.Client.desktop',
       'org.gnome.Nautilus.desktop',
       'org.gnome.Calendar.desktop',
       'org.gnome.Maps.desktop',
       'org.gnome.Books.desktop',
       'org.gnome.Games.desktop',
       'transmission-remote-gtk.desktop',
       'org.gnome.Terminal.desktop']

flatpak_remotes: >-
  {{ groupvars.all.flatpak_remotes
   | combine(private.flatpak_remotes)
  }}

flatpak_apps: >-
  {{ groupvars.all.flatpak_apps
   | union(private.flatpak_apps)
  }}

gnome_settings: >-
  {{ groupvars.all.gnome_settings
   | combine(private.gnome_settings)
  }}
